import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

@Schema()
export class Pokemon extends Document {
  // id: string; // This is not needed because it is automatically generated by MongoDB
  @Prop({
    index: true,
    required: true,
    unique: true,
  })
  name: string;
  @Prop({
    index: true,
    required: true,
    unique: true,
  })
  no: number;
}

export const PokemonSchema = SchemaFactory.createForClass(Pokemon);
